baseURL: https://cpssd.net
<<<<<<< HEAD
languageCode: en-us
=======
disablePathToLower: true
languageCode: en-ie
>>>>>>> 842ac2d6d56cd309f322a44976cd8f876060b4c0
title: The Unofficial CPSSD Homepage
theme: cpssd
params:
  description: |
    Computational Problem Solving and Software Development (CPSSD) is an
    undergraduate computing course in Dublin City University. It is aimed at
    applicants with prior programming experience, and is generally the hippest
    place to be this side of Ballymaloe.
  links:
    - name: Learn More
      location: /about
    - name: Students
      location: /students
